import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        padding: 20,
        backgroundColor: "#fff",
        paddingBottom: 70,
        position: "relative",
    },
    title: {
        fontSize: 24,
        fontWeight: "bold",
        marginBottom: 20,
    },
    menuButton: {
        backgroundColor: "#007BFF",
        padding: 15,
        borderRadius: 10,
        marginBottom: 10,
        width: "100%",
        alignItems: "center",
    },
    fineTuneButton: {
        backgroundColor: "#009900",
        padding: 15,
        borderRadius: 10,
        marginBottom: 10,
        width: "100%",
        alignItems: "center",
    },
    menuButtonText: {
        color: "#fff",
        fontSize: 16,
        fontWeight: "600",
        textAlign: "center",
    },
    subMenuButton: {
        backgroundColor: "#E0E0E0",
        padding: 15,
        borderRadius: 10,
        marginBottom: 10,
        width: "100%",
        alignItems: "center",
    },
    subMenuButtonText: {
        color: "#333",
        fontSize: 16,
        fontWeight: "600",
        textAlign: "center",
    },
    backButton: {
        backgroundColor: "#ccc",
        padding: 10,
        borderRadius: 5,
        width: "100%",
        alignItems: "center",
        position: "absolute",
        bottom: 25,
        zIndex: 1,
    },
    backButtonText: {
        color: "#333",
        fontSize: 16,
        fontWeight: "600",
        textAlign: "center",
    },
    input: {
        borderWidth: 1,
        borderColor: "#ccc",
        borderRadius: 5,
        padding: 10,
        width: "100%",
        marginBottom: 20,
        backgroundColor: "#f9f9f9",
    },
    imagePicker: {
        backgroundColor: "#007BFF",
        padding: 15,
        borderRadius: 10,
        marginBottom: 10,
        width: "100%",
        alignItems: "center",
    },
    imagePickerText: {
        color: "#fff",
        fontSize: 16,
        fontWeight: "600",
        textAlign: "center",
    },
    submitButton: {
        backgroundColor: "#28a745",
        padding: 15,
        borderRadius: 10,
        marginBottom: 10,
        width: "100%",
        alignItems: "center",
    },
    submitButtonText: {
        color: "#fff",
        fontSize: 16,
        fontWeight: "600",
        textAlign: "center",
    },
    thumbnail: {
        width: 100,
        height: 100,
        marginBottom: 20,
        borderRadius: 5,
    },
    listItem: {
        padding: 15,
        borderBottomWidth: 2,
        borderBottomColor: "#eee",
        flexDirection: "row",
        alignItems: "center",
    },
    listText: {
        fontSize: 24,
        fontWeight: "400",
        color: "#333",
        marginLeft: 10,
    },
    profileImage: {
        width: 50,
        height: 50,
        borderRadius: 25,
    },
    profileImagePlaceholder: {
        width: 50,
        height: 50,
        borderRadius: 25,
        backgroundColor: "#ccc",
        justifyContent: "center",
        alignItems: "center",
    },
    detailsContainer: {
        marginTop: 20,
        alignItems: "center",
        padding: 15,
        borderWidth: 1,
        borderColor: "#eee",
        borderRadius: 10,
        backgroundColor: "#f9f9f9",
        width: "100%",
        maxWidth: 400,
    },
    profileImageDetails: {
        width: 100,
        height: 100,
        borderRadius: 50,
        marginBottom: 15,
    },
    locationThumbnail: {
        width: 100,
        height: 100,
        borderRadius: 10,
        marginBottom: 10,
    },
    deleteButton: {
        backgroundColor: "#FF4D4D",
        padding: 10,
        borderRadius: 5,
        marginTop: 20,
        width: "100%",
        alignItems: "center",
    },
    deleteButtonText: {
        color: "#fff",
        fontWeight: "600",
        textAlign: "center",
    },
    approveButton: {
        backgroundColor: "#4CAF50",
        padding: 10,
        borderRadius: 5,
        marginTop: 20,
        width: "100%",
        alignItems: "center",
    },
    approveButtonText: {
        color: "#fff",
        fontWeight: "600",
        textAlign: "center",
    },
    rejectButton: {
        backgroundColor: "#FF9800",
        padding: 10,
        borderRadius: 5,
        marginTop: 20,
        width: "100%",
        alignItems: "center",
    },
    rejectButtonText: {
        color: "#fff",
        fontWeight: "600",
        textAlign: "center",
    },
    postImage: {
        width: 200,
        height: 200,
        resizeMode: "cover",
        marginRight: 10,
        alignSelf: "center",
    },
    closeButton: {
        position: 'absolute',
        top: 10,
        right: 10,
        backgroundColor: 'transparent',
        padding: 10,
        zIndex: 10,
    },
    closeButtonText: {
        fontSize: 20,
        color: 'black',
    },
    modalContainer: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "rgba(0, 0, 0, 0.5)",
    },
    modalContent: {
        width: "90%",
        padding: 20,
        backgroundColor: "#fff",
        borderRadius: 10,
        alignItems: "center",
    },
    modalTitle: {
        fontSize: 18,
        fontWeight: "bold",
        color: "#333",
        marginBottom: 15,
    },
    modalActions: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginTop: 20,
        width: "100%",
    },
    modalButton: {
        flex: 1,
        padding: 15,
        borderRadius: 10,
        alignItems: "center",
        marginHorizontal: 5,
    },
    confirmButton: {
        backgroundColor: "#fff",
    },
    confirmButtonText: {
        color: "#009900",
        fontWeight: "600",
        fontSize: 16,
    },
    cancelButton: {
        backgroundColor: "#fff",
    },
    cancelButtonText: {
        color: "#ff0000",
        fontWeight: "600",
        fontSize: 16,
    },
    detailsText: {
        fontSize: 16,
        color: "#555",
        marginBottom: 10,
    },
    zoomButton: {
        position: "absolute",
        bottom: 20,
        backgroundColor: "#007BFF",
        borderRadius: 50,
        padding: 15,
        alignItems: "center",
        justifyContent: "center",
    },
    zoomButtonText: {
        color: "#fff",
        fontSize: 18,
        fontWeight: "bold",
    },


});

export default styles;