import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    marginTop: 0,
    flex: 1,
    padding: 0,
  },
  map: {
    flex: 1,
  },
  buttonContainer: {
    position: "absolute",
    bottom: 100,
    right: 0,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    width: "20%",
  },
  button: {
    backgroundColor: "#FF6B6B",
    padding: 10,
    borderRadius: 10,
    alignItems: "center",
    marginHorizontal: 1,
  },
  buttonText: {
    color: "#fff",
    fontSize: 20,
    fontWeight: "bold",
  },
  iconStyle: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: [{ translateX: -150 }, { translateY: -100 }],
    width: 300,
    padding: 20,
    backgroundColor: "white",
    borderRadius: 10,
    shadowColor: "#000",
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 5,
  },
  closeButton: {
    marginTop: 10,
    padding: 10,
    backgroundColor: "red",
    borderRadius: 5,
  },
  searchContainer: {
    gap: 15,
    width: "100%",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    padding: 15,
    backgroundColor: "#F1F0E8",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
  },
  searchInput: {
    flex: 5,
    height: 50,
    borderRadius: 10,
    paddingHorizontal: 15,
    fontSize: 16,
    color: "#333",
    backgroundColor: "#E5E1DA",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.35,
    shadowRadius: 4,
    elevation: 2,
  },
  searchButton: {
    flex: 1,
    height: 50,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#E5E1DA",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.35,
    shadowRadius: 5,
    elevation: 3,
  },
  suggestionsContainer: {
    backgroundColor: "#F1F0E8",
    padding: 10,
    gap: 10,
    borderRadius: 10,
    width: "100%",
  },
  suggestionItem: {
    backgroundColor: "#E5E1DA",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginBottom: 0,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.35,
    shadowRadius: 3,
    elevation: 2,
  },
  suggestionText: {
    fontSize: 16,
    color: "#333",
    fontWeight: "lightweight",
    marginBottom: 5,
  },
  markercontaine: {
    position: "absolute",
    top: 100,
    bottom: 112,
    width: "auto",
    marginHorizontal: 10,
    padding: 10,
    backgroundColor: "#F1F0E8",
    borderRadius: 36,
    shadowColor: "#000",
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 5,
  },
  popupcontainer: {
    backgroundColor: "#F1F0E8",
    borderRadius: 36,
    padding: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
    gap: 20,
    marginTop: 5,
  },
  popupcontainer2: {
    gap: 20,
  },
  imagetextbg: {
    backgroundColor: "rgba(124, 124, 124, 0.6)",
    padding: 10,
    borderRadius: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    left: 20,
    bottom: 20,
  },
  userid_star: {
    display: "flex",
    width: 219,
    height: 40,
    padding: 10,
    alignItems: "center",
    borderRadius: 36,
    backgroundColor: "#89A8B2",
    borderBlockColor: "#fff",
  },

  container2: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#E5E1DA",
    borderWidth: 2,
    borderRadius: 30,
    borderColor: "#B3C8CF",
    borderStyle: "dotted",
    padding: 10,
    margin: 10,
    width: "auto",
    height: 60,
  },
  profileImage: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 10,
  },
  username: {
    flex: 1,
    color: "rgba(49, 49, 49, 0.6)",
    fontSize: 16,
    fontWeight: "600",
  },
  linkIcon: {
    width: 30,
    height: 30,
    backgroundColor: "#E5E1DA",
    borderRadius: 15,
    justifyContent: "center",
    alignItems: "center",
  },
  linkText: {
    fontSize: 18,
    color: "#FFFFFF",
  },
  commentstyle: {
    padding: 10,
    borderRadius: 10,
    marginBottom: 10,
    width: "100%",
    backgroundColor: "#E5E1DA",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.35,
    shadowRadius: 5,
    elevation: 3,
  },

  header: { fontSize: 18, fontWeight: "bold" },
  ratingContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 10,
  },
  label: { fontSize: 16, marginRight: 10 },
  starsContainer: { flexDirection: "row" },
});

export default styles;
